import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import AppLayout from '../../layouts/AppLayout';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Avatar from '../../components/ui/Avatar';
import useExpenseCalc from '../../hooks/useExpenseCalc';
import { useGroup } from '../../context/GroupContext';
import { useAuth } from '../../context/AuthContext';
import { formatCurrency } from '../../utils/currency';
import { getDisplayName } from '../../utils/displayName';
import { useToast } from '../../components/ui/Toast';

export default function SettleUp() {
  const { groupId } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const { showToast } = useToast();
  const { setActiveGroup, activeGroup, members, expenses, settlements, addSettlement, updateSettlement } = useGroup();
  const { balances, suggestedPayments } = useExpenseCalc(members, expenses, settlements);
  const [recording, setRecording] = React.useState(null);
  const [phoneNumber, setPhoneNumber] = useState('');

  React.useEffect(() => {
    setActiveGroup(groupId);
  }, [groupId, setActiveGroup]);

  const handleSettle = (fromId, toId, amount) => {
    const existing = settlements.find(
      (s) => s.fromUserId === fromId && s.toUserId === toId && s.status === 'pending'
    );
    if (existing) {
      updateSettlement(existing.id, { status: 'completed', settledAt: new Date().toISOString() });
    } else {
      addSettlement(groupId, {
        fromUserId: fromId,
        toUserId: toId,
        amount,
        note: 'Manual settlement',
        status: 'completed',
        settledAt: new Date().toISOString(),
      });
    }
    const fromName = getDisplayName(fromId, members);
    const toName = getDisplayName(toId, members);
    showToast(`Settlement of ${formatCurrency(amount)} from ${fromName} to ${toName} recorded!`, 'success');
  };

  const validatePhone = (phone) => {
    const cleaned = phone.replace(/[\s\-\(\)]/g, '');
    return /^(\+?\d{7,15})$/.test(cleaned);
  };

  const handleWhatsAppShare = () => {
    const cleaned = phoneNumber.replace(/[\s\-\(\)]/g, '');
    if (!validatePhone(cleaned)) {
      showToast('Please enter a valid phone number', 'error');
      return;
    }
    const summaryLines = suggestedPayments.map((p) => {
      const fromName = getDisplayName(p.from, members);
      const toName = getDisplayName(p.to, members);
      return `${fromName} owes ${toName} ${formatCurrency(p.amount)}`;
    });
    const message = `SplitMate Settlement Summary\n\nTrip: ${activeGroup?.name || 'Group'}\n\n${summaryLines.join('\n')}\n\nGenerated by SplitMate`;
    const encoded = encodeURIComponent(message);
    const phone = cleaned.startsWith('+') ? cleaned.substring(1) : cleaned;
    const url = `https://wa.me/${phone}?text=${encoded}`;
    window.open(url, '_blank');
  };

  if (!activeGroup) {
    return (
      <AppLayout userName={user?.displayName || 'User'}>
        <div className="text-center py-16"><p className="text-4xl mb-3">🔍</p><p className="text-gray-600 dark:text-gray-300">Group not found</p></div>
      </AppLayout>
    );
  }

  const userBalance = balances[user?.id] || 0;
  const youAreOwed = suggestedPayments.filter((p) => p.to === user?.id);
  const youOwe = suggestedPayments.filter((p) => p.from === user?.id);

  const settlementSummary = suggestedPayments.map((p) => {
    const fromName = getDisplayName(p.from, members);
    const toName = getDisplayName(p.to, members);
    return `${fromName} owes ${toName} ${formatCurrency(p.amount)}`;
  });

  const whatsappMessage = settlementSummary.length > 0
    ? `SplitMate Settlement Summary\n\nTrip: ${activeGroup.name}\n\n${settlementSummary.join('\n')}\n\nGenerated by SplitMate`
    : '';

  return (
    <AppLayout userName={user?.displayName || 'User'}>
      <div className="pt-1">
        <div className="flex items-center gap-3 mb-4">
          <button onClick={() => navigate(`/groups/${groupId}`)} className="w-9 h-9 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center text-gray-700 dark:text-gray-200">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="15 18 9 12 15 6" />
            </svg>
          </button>
          <div className="flex-1">
            <h1 className="text-xl font-bold text-gray-900 dark:text-white">Settle Up</h1>
            <p className="text-xs text-gray-600 dark:text-gray-300">{activeGroup.name}</p>
          </div>
        </div>

        <Card padding="p-5" className="mb-4 text-center">
          <p className="text-sm text-gray-600 dark:text-gray-300 mb-1">Your balance in this group</p>
          <p className={`text-3xl font-bold ${userBalance >= 0 ? 'text-green-600' : 'text-red-600'}`}>
            {userBalance >= 0 ? '+' : ''}{formatCurrency(userBalance)}
          </p>
        </Card>

        {suggestedPayments.length === 0 ? (
          <div className="text-center py-12">
            <p className="text-4xl mb-3">🎉</p>
            <p className="text-gray-600 dark:text-gray-300 font-medium">All settled up!</p>
            <p className="text-sm text-gray-500 dark:text-gray-300 mt-1">No pending payments</p>
          </div>
        ) : (
          <div className="space-y-3">
            {youOwe.length > 0 && (
              <Card padding="p-4">
                <p className="text-xs font-semibold text-red-500 uppercase tracking-wide mb-3">You owe</p>
                <div className="space-y-2">
                  {youOwe.map((p, i) => {
                    const toName = getDisplayName(p.to, members);
                    return (
                      <div key={i} className="flex items-center justify-between py-2">
                        <div className="flex items-center gap-2">
                          <Avatar name={toName} size="sm" />
                          <span className="text-sm font-medium">{toName}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-semibold text-red-600">{formatCurrency(p.amount)}</span>
                          <Button size="sm" onClick={() => handleSettle(p.from, p.to, p.amount)}>Pay</Button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </Card>
            )}

            {youAreOwed.length > 0 && (
              <Card padding="p-4">
                <p className="text-xs font-semibold text-green-500 uppercase tracking-wide mb-3">You are owed</p>
                <div className="space-y-2">
                  {youAreOwed.map((p, i) => {
                    const fromName = getDisplayName(p.from, members);
                    return (
                      <div key={i} className="flex items-center justify-between py-2">
                        <div className="flex items-center gap-2">
                          <Avatar name={fromName} size="sm" />
                          <span className="text-sm font-medium">{fromName}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-semibold text-green-600">{formatCurrency(p.amount)}</span>
                          <Button size="sm" variant="secondary" onClick={() => handleSettle(p.from, p.to, p.amount)}>Record</Button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </Card>
            )}

            {suggestedPayments.length > 0 && (
              <Card padding="p-4">
                <p className="text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-3">All suggested payments</p>
                <div className="space-y-2">
                  {suggestedPayments.map((p, i) => {
                    const fromName = getDisplayName(p.from, members);
                    const toName = getDisplayName(p.to, members);
                    return (
                      <div key={i} className="flex items-center justify-between py-2 text-sm">
                        <span className="text-gray-700 dark:text-gray-200">{fromName} → {toName}</span>
                        <span className="font-semibold">{formatCurrency(p.amount)}</span>
                      </div>
                    );
                  })}
                </div>
              </Card>
            )}
          </div>
        )}

        {settlements.filter((s) => s.status === 'completed').length > 0 && (
          <button
            onClick={() => navigate(`/groups/${groupId}/settlements`)}
            className="w-full mt-4 py-3 text-sm text-primary-600 font-medium text-center"
          >
            View Settlement History →
          </button>
        )}

        {suggestedPayments.length > 0 && (
          <Card padding="p-4" className="mt-4">
            <p className="text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-3">
              Settlement Summary
            </p>
            <div className="space-y-2">
              {suggestedPayments.map((p, i) => {
                const fromName = getDisplayName(p.from, members);
                const toName = getDisplayName(p.to, members);
                return (
                  <div key={i} className="flex items-center gap-2 text-sm bg-gray-50 dark:bg-gray-700/50 rounded-xl px-3 py-2">
                    <span className="text-lg">💸</span>
                    <span className="text-gray-700 dark:text-gray-200">
                      <span className="font-medium">{fromName}</span> owes <span className="font-medium">{toName}</span>{' '}
                      <span className="font-semibold text-primary-600">{formatCurrency(p.amount)}</span>
                    </span>
                  </div>
                );
              })}
            </div>
          </Card>
        )}

        {suggestedPayments.length > 0 && (
          <Card padding="p-4" className="mt-3">
            <p className="text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-3">
              Share Settlement Summary
            </p>
            <div className="space-y-3">
              <div>
                <label className="block text-sm text-gray-600 dark:text-gray-300 mb-1.5">Phone Number</label>
                <input
                  type="tel"
                  value={phoneNumber}
                  onChange={(e) => setPhoneNumber(e.target.value)}
                  placeholder="+919876543210 or 9876543210"
                  className="w-full px-4 py-2.5 text-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-400 border border-gray-200 dark:border-gray-600 rounded-xl outline-none focus:border-primary-500 transition-all"
                />
              </div>
              <Button
                fullWidth
                onClick={handleWhatsAppShare}
                className="flex items-center justify-center gap-2"
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
                </svg>
                Send to WhatsApp
              </Button>
            </div>
          </Card>
        )}
      </div>
    </AppLayout>
  );
}
